name: Integration test
run-name: "Testing PR #${{ github.event.client_payload.slash_command.args.named.pr-number }}"

on:
  repository_dispatch:
    types: [integration-test-command]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Output command and arguments
        run: |
          echo "PR number: ${{ github.event.client_payload.slash_command.args.named.pr-number }}"
          echo "Comment id: ${{ github.event.client_payload.slash_command.args.named.comment-id }}"
          echo "Branch: ${{ github.event.client_payload.slash_command.args.named.branch }}"
      - run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
