name: Integration test

on:
  pull_request:
    types: [ready_for_review]
    paths:
      - test.js

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo "Test completed"
