name: Handle slash commands

on:
  issue_comment:
    types: [created]

jobs:
  get_docker_repository_refs:
    runs-on: ubuntu-22.04
    outputs:
      usergram_docker_ref: ${{ steps.get_args.outputs.usergram_docker_ref || 'master'}}
      user_app_server_side_ref: ${{ steps.get_args.outputs.user_app_server_side_ref || 'master'}}
      gram_agent_ref: ${{ steps.get_args.outputs.gram_agent_ref || 'master'}}
      usergram_e2e_ref: ${{ steps.get_args.outputs.usergram_e2e_ref || 'master' }}
      usergram_user_journey_service_ref: ${{ steps.get_args.outputs.usergram_user_journey_service_ref || 'main'}}
    env:
      COMMENT: ${{ github.event.comment.body }}
    steps:
      - name: Get args from slash command
        id: get_args
        run: |
          # Strip `/e2e ` from PR comment to get args, and convert to array
          args=(${COMMENT:5})

          for arg in "${args[@]}"
          do
            echo "$arg" >> $GITHUB_OUTPUT
          done

  test:
    needs: get_docker_repository_refs
    runs-on: ubuntu-22.04
    env:
      USERGRAM_DOCKER_REF: ${{ needs.get_docker_repository_refs.outputs.usergram_docker_ref }}
      USER_APP_SERVER_SIDE_REF: ${{ needs.get_docker_repository_refs.outputs.user_app_server_side_ref }}
      GRAM_AGENT_REF: ${{ needs.get_docker_repository_refs.outputs.gram_agent_ref }}
      USERGRAM_E2E_REF: ${{ needs.get_docker_repository_refs.outputs.usergram_e2e_ref }}
      USERGRAM_USER_JOURNEY_SERVICE_REF: ${{ needs.get_docker_repository_refs.outputs.usergram_user_journey_service_ref }}
    steps:
      - name: Test
        run: |
          echo "usergram docker: $USERGRAM_DOCKER_REF"
          echo "user app: $USER_APP_SERVER_SIDE_REF"
          echo "gram agent: $GRAM_AGENT_REF"
          echo "usergram e2e: $USERGRAM_E2E_REF"
          echo "journey: $USERGRAM_USER_JOURNEY_SERVICE_REF"
