name: integration-test

on:
  issue_comment:
    types: [created]

env:
  COMMENT: ${{ github.event.comment.body }}

jobs:
  test:
    if: ${{ github.event.issue.pull_request && (contains(github.event.comment.body, '/it') || contains(github.event.comment.body, '/integration-test')) }}
    runs-on: ubuntu-22.04
    env:
      SHOULD_RECORD: ${{ contains(github.event.comment.body, 'record') }}
    steps:
      - run: echo $COMMENT
      - run: echo "should record $SHOULD_RECORD"
