name: Test

on:
  issue_comment:
    types: [created]

jobs:
  read_comment:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/ut') }}
    runs-on: ubuntu-latest
    outputs:
      pr_base_sha: ${{ steps.comment-branch.outputs.base_sha }}
      pr_head_sha: ${{ steps.comment-branch.outputs.head_sha }}
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - run: |
          echo ${{ steps.comment-branch.outputs.base_sha }}
          echo ${{ steps.comment-branch.outputs.head_sha }}
