name: integration-test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      COMMENT: "/it --record"
      WTF: "/it"
    steps:
      - run: |
          # Strip `/it` from PR comment to get params, and convert to array
          params=(${COMMENT:4})
          echo "${params[@]}"

          params2=(${WTF:4})
          echo "${params2[@]}"
