name: Deploy to eai-dev
run-name: ${{ inputs.apps }}

on:
  workflow_dispatch:
    inputs:
      apps:
        description: >-
          Apps to be deploy (e.g. search,packages). 
          To see available apps:
          (echo packages && find apps -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | grep -v "_boilerplate")
        required: true
        default: ""
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup APPS_TO_DEPLOY
        run: |
          apps="${{ github.event.inputs.apps }}"
          IFS=',' read -r -a APPS_TO_DEPLOY <<< "$apps"

          # Array is not permitted in $GITHUB_ENV
          echo "APPS_TO_DEPLOY=$(IFS=' '; echo "${APPS_TO_DEPLOY[@]}")" >> $GITHUB_ENV
      - name: Deploy information
        run: |
          echo "- App to deploy: ${APPS_TO_DEPLOY}"
          echo "- Dev environment: ${{ github.event.inputs.k8s_namespace }}"
          echo "- Branch: ${GITHUB_REF#refs/heads/}"
