name: Test

on:
  issue_comment:
    types: [created]

jobs:
  read_comment:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/ut') }}
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-apps.outputs.apps }}
      # should_build_pkgs: ${{ steps.set-apps.outputs.should_build_pkgs }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy information
        id: set-apps
        shell: bash
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          apps=("search" "host")
          apps_json=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -s .)
          echo $apps_json
          # echo "apps=$apps_json" >> $GITHUB_OUTPUT
          # echo 'apps=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"
          # echo 'apps=$apps_json' >> "$GITHUB_OUTPUT"
          echo 'apps=["red", "green", "blue"]'
          echo 'apps=$apps_json'

  # build:
  #   needs: read_comment
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       app: ${{ fromJson(needs.read_comment.outputs.apps) }}
  #       should_build_pkgs: ${{ fromJson(needs.read_comment.outputs.should_build_pkgs) }}

  #   steps:
  #     - name: Display the current app and build setting
  #       run: |
  #         echo "App: ${{ matrix.app }}"
  #         # echo "Should Build Packages: ${{ matrix.should_build_pkgs }}"
