name: Deploy to eai-dev
run-name: >-
  ${{ format('My Regression tests: {0}', inputs.k8s_namespace) }}

on:
  workflow_dispatch:
    inputs:
      k8s_namespace:
        type: choice
        required: true
        description: "k8s namespace to update"
        options:
          - eai-dev-apark
          - eai-dev-blackjack
          - eai-dev-client-announcement
          - eai-dev-design
          - eai-dev-fixers
          - eai-dev-kaizen
          - eai-dev-infra-check
          - dev-eks-eai
          - dev-eks-eai-demo
      host:
        description: "host"
        required: false
        type: boolean
      settings:
        description: "settings"
        required: false
        type: boolean
      journey:
        description: "journey"
        required: false
        type: boolean
      search:
        description: "search"
        required: false
        type: boolean
      stats:
        description: "stats"
        required: false
        type: boolean
      funnel:
        description: "funnel"
        required: false
        type: boolean

env:
  S3_BUCKET: usergram-front-v3-${{ github.event.inputs.k8s_namespace }}
  APP_TO_DEPLOY: ${{ github.event.inputs.app_to_deploy }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
