name: Deploy to eai-dev
run-name: >-
  ${{ inputs.k8s_namespace }}: ${{ inputs.apps }}

on:
  workflow_dispatch:
    inputs:
      k8s_namespace:
        type: choice
        required: true
        description: "k8s namespace to update"
        options:
          - eai-dev-apark
          - eai-dev-blackjack
          - eai-dev-client-announcement
          - eai-dev-design
          - eai-dev-fixers
          - eai-dev-kaizen
          - eai-dev-infra-check
          - dev-eks-eai
          - dev-eks-eai-demo
      apps:
        description: >-
          Apps to be deploy (e.g. search,packages). \nToo see available apps:\n\n echo packages && find apps -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | grep -v "_boilerplate"
        required: false
        default: ""
        type: string

env:
  S3_BUCKET: usergram-front-v3-${{ github.event.inputs.k8s_namespace }}
  APPS: ${{ github.event.inputs.apps }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $APPS
