name: Deploy to eai-dev
run-name: >-
  ${{ (inputs.host || inputs.packages) && 'host' || '' }}
  ${{ inputs.settings && 'settings' || '' }}

on:
  workflow_dispatch:
    inputs:
      host:
        description: "host"
        required: false
        type: boolean
      packages:
        description: "packages"
        required: false
        type: boolean
      settings:
        description: "settings"
        required: false
        type: boolean
      journey:
        description: "journey"
        required: false
        type: boolean
      search:
        description: "search"
        required: false
        type: boolean
      stats:
        description: "stats"
        required: false
        type: boolean
      funnel:
        description: "funnel"
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ github.event.inputs.host }} == "true" || ${{ github.event.inputs.packages }} == "true" ]]; then echo 'host'; fi
