name: Test

on:
  # issue_comment:
  #   types: [created]
  pull_request:

jobs:
  read_comment:
    # if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/ut') }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      # should_build_pkgs: ${{ steps.set-apps.outputs.should_build_pkgs }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare matrix
        id: set-matrix
        shell: bash
        env:
          # COMMENT: ${{ github.event.comment.body }}
          COMMENT: "/ut search host funnel"
        run: |
          # apps_string="${COMMENT:4}"
          # apps_array_string=$(echo "$apps_string" | sed 's/ /, /g' | sed 's/^/[ /' | sed 's/$/ ]/')
          # echo "apps=$apps_array_string" >> $GITHUB_OUTPUT

          # echo "matrix={\"workspace\":[{\"search\",\"host\"]}" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":[{\"workspace\":\"search\",\"should_build_pkgs\":true},{\"workspace\":\"host\",\"should_build_pkgs\":false}]}"  >> $GITHUB_OUTPUT
  build:
    needs: read_comment
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.read_comment.outputs.matrix) }}

    steps:
      - name: Display the current app and build setting
        run: |
          echo "App: ${{ matrix.workspace }}"
          echo "Should Build Packages: ${{ matrix.should_build_pkgs }}"
