name: Test

on:
  pull_request:

jobs:
  unit-test-report:
    name: Lint and unit test report
    runs-on: ubuntu-22.04
    steps:
      - name: Set latest commit status
        env:
          SUCCESS: ${{ ('success' == "success" || 'a' == "skipped") && "success" || "failure" }}
          SKIPPED: ${{ ('a' == "success" || 'skipped' == "skipped") && "success" || "failure" }}
          FAILURE: ${{ ('b' == "success" || 'a' == "skipped") && "success" || "failure" }}
        run: |
          echo $SUCCESS
          echo $SKIPPED
          echo $FAILURE
