name: integration-test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      COMMENT: "/it --record"
      WTF: "/it"
    steps:
      - run: |
          params=(${COMMENT:4})
          echo "${params[@]}"
          params2=(${WTF:4})
          echo "${params2[@]}"
